{% set name = "assyst" %}
{% set version = "0.3.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/assyst-{{ version }}.tar.gz
  sha256: b42efa7b1d72f377cfd7af6550215046941a805bd10a715db63dfa345cc6589c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }},<3.13
    - structuretoolkit ==0.0.32
    - tqdm >=4,<5
    - ase >=3,<4
    - matplotlib-base >=3,<4
    - numpy >1,<3
    - pandas >=2.2,<3

test:
  imports:
    - assyst
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eisenforschung/assyst
  summary: A minimal reference implementation of ASSYST method to generate transferable training data for machine learning potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmrv
