{% set name = "assyst" %}
{% set version = "0.6.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/assyst-{{ version }}.tar.gz
  sha256: 29bcaa4f2d4394528e9b3c6a8938ce0310af39878fbd2311cca7eee4808d21d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }},<3.13
    - structuretoolkit ==0.0.34
    - pyxtal >=1,<1.2.0
    - tqdm >=4,<5
    - ase >=3,<4
    - matplotlib-base >=3,<4
    - numpy >1,<3
    - pandas >=2.2,<3
    - matscipy >=1,<2

test:
  imports:
    - assyst
  commands:
    - pip check
    - python -m unittest discover test
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eisenforschung/assyst
  summary: A minimal reference implementation of ASSYST method to generate transferable training data for machine learning potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmrv
