{% set name = "assyst" %}
{% set version = "0.14.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/assyst-{{ version }}.tar.gz
  sha256: 4e2955522bc436c11e324bfb0f7ccf1ef15853c52edced5a1b3bb7716d1ee96b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - seaborn >=0.13,<1
    - pyiron_snippets >=1,<2
    - python >={{ python_min }},<3.14
    - pyxtal >=1,<1.2.0
    - tqdm >=4,<5
    - ase >=3,<4
    - matplotlib-base >=3,<4
    - numpy >1,<3
    - pandas >=2,<4

test:
  imports:
    - assyst
  source_files:
    - tests
  commands:
    - "pip install assyst[test]"
    - pip check
    - python -m unittest discover tests
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eisenforschung/assyst
  summary: A minimal reference implementation of the ASSYST method to generate transferable training data for machine learning potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmrv
